"""Task data + behavior.

`TaskData` is the wire half: a frozen pydantic model carrying the data which
initializes a task instance. Rides on `trace.task.data` in `traces.jsonl`.

`Task` is the behavior half: runtime prep (`setup`/`finalize`), tool servers
(`toolsets`), and scoring (`@reward`/`@metric`) methods.
"""

from __future__ import annotations

import copy
import inspect
import logging
from collections.abc import Mapping
from typing import TYPE_CHECKING, ClassVar, Generic, Self

from pydantic import BaseModel, ConfigDict, Field
from typing_extensions import TypeVar

from verifiers.v1.configs.task import TaskConfig
from verifiers.v1.errors import TaskError, boundary
from verifiers.v1.state import StateT
from verifiers.v1.types import Messages, content_text
from verifiers.v1.utils.artifacts import Artifact
from verifiers.v1.utils.decorators import discover_decorated, invoke_all
from verifiers.v1.utils.generic import concrete_type

if TYPE_CHECKING:
    from contextlib import AbstractAsyncContextManager

    from verifiers.v1.judge import Judge
    from verifiers.v1.mcp import Toolset
    from verifiers.v1.runtimes import Runtime, RuntimeConfig
    from verifiers.v1.trace import Trace

logger = logging.getLogger(__name__)


class TaskResources(BaseModel):
    """Optional resource limits for the task."""

    model_config = ConfigDict(frozen=True)

    cpu: float | None = None
    """CPU cores."""
    memory: float | None = None
    """Memory in GB."""
    gpu: str | None = None
    """GPU spec, e.g. "A100" or "A100:2" (type[:count])."""
    disk: float | None = None
    """Disk in GB (enforced by prime; advisory on docker/modal)."""


class TaskTimeout(BaseModel):
    """Optional per-task timeout overrides, in seconds."""

    model_config = ConfigDict(frozen=True)

    setup: float | None = None
    """Timeout (in seconds) for the task's setup hook."""
    agent: float | None = None
    """Timeout (in seconds) for the agent's solve attempt."""
    finalize: float | None = None
    """Timeout (in seconds) for the task's finalize hook."""
    scoring: float | None = None
    """Timeout (in seconds) for the task's scoring."""


class TaskData(BaseModel):
    model_config = ConfigDict(frozen=True)

    idx: int | None = None
    """Taskset-autogenerated index."""
    name: str | None = None
    """Optional human-readable task name."""
    description: str | None = None
    """Optional human-readable task description."""

    prompt: str | Messages | None = None
    """Initial user prompt; unset if the user opens the conversation."""
    system_prompt: str | None = None
    """Optional system prompt to prepend to the user prompt."""

    image: str | None = None
    """Optional Docker image to use for the task. Only relevant for tasks that run in a container."""
    workdir: str | None = None
    """Optional working directory to use for the task. Only relevant for tasks that run in a container."""

    network_allow: list[str] = Field(default_factory=lambda: ["*"])
    """Execution-time destinations requested by this task. `*` leaves the runtime
    allowlist unchanged; a concrete list replaces a wildcard or combines with existing
    entries. Prime runtimes accept host-level entries and require `vm=true`."""
    network_block: list[str] = Field(default_factory=list)
    """Execution-time destinations denied by this task and combined with runtime
    blocks. Non-empty concrete allowlists cannot be combined with blocklists. Docker
    framework routes take precedence; ordinary Prime deny rules pass through unchanged."""

    artifacts: list[Artifact] = Field(default_factory=list)
    """Paths collected from one runtime and restored at the same locations in another,
    on top of the implicitly collected `/logs/artifacts/` convention dir. Declare
    runtime outputs that must cross that boundary. A declared path that is missing at
    collection time fails the rollout."""

    timeout: TaskTimeout = TaskTimeout()
    resources: TaskResources = TaskResources()

    @property
    def prompt_text(self) -> str:
        if isinstance(self.prompt, str):
            return self.prompt
        texts = [content_text(message.content) for message in self.prompt or []]
        return "\n\n".join(text for text in texts if text)


class WireTaskData(TaskData):
    """Wire form that preserves task-specific fields without importing the task class."""

    model_config = ConfigDict(extra="allow")


DataT = TypeVar("DataT", bound=TaskData)
ConfigT = TypeVar("ConfigT", bound=TaskConfig, default=TaskConfig)


class Task(Generic[DataT, StateT, ConfigT]):
    NEEDS_CONTAINER: ClassVar[bool] = False
    """Whether the task needs a containerized environment (isolated filesystem, ...)."""

    def __init__(self, data: DataT, config: ConfigT | None = None) -> None:
        self.data = data
        self.config = config if config is not None else self.config_type()()

    def with_system_prompt(self, system_prompt: str) -> Self:
        clone = copy.copy(self)
        clone.data = self.data.model_copy(update={"system_prompt": system_prompt})
        return clone

    async def setup(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def finalize(self, trace: Trace, runtime: Runtime) -> None:
        return None

    async def validate(self, runtime: Runtime) -> bool:
        return True

    def scoring_runtime(
        self, runtime: Runtime, base_runtime_config: RuntimeConfig
    ) -> AbstractAsyncContextManager[Runtime] | None:
        """A box to score this task in, instead of the one the agent worked in.

        `None` (the default) keeps scoring where it has always happened: the agent's own
        runtime, alive and exactly as the agent left it. Return a context manager and
        the rollout scores the task inside it instead — for a grader the agent must not
        be able to reach, since anything living in a box the agent had root in is
        reachable, and hiding individual files only moves the target.

        Whatever has to survive the move is the task's problem: carry it with
        `collect`/`restore` while the agent's box is still up, inside the context
        manager. `base_runtime_config` is the resolved run-level config, before the
        current task's overrides, so the new box can distinguish task-declared resources
        from CLI overrides; `runtime.config` alone cannot.

        Only `score` moves. `finalize` and the harness's own scoring stay on `runtime`,
        which is what they describe."""
        return None

    async def score(
        self,
        trace: Trace,
        runtime: Runtime | None = None,
    ) -> None:
        def requires_runtime(fn) -> bool:
            param = inspect.signature(fn).parameters.get("runtime")
            # A defaulted runtime parameter can still be called offline with None.
            return param is not None and param.default is inspect.Parameter.empty

        judges = self.plugged_judges()
        available = {"task": self.data, "trace": trace}
        if runtime is not None:
            available["runtime"] = runtime

        async with boundary(TaskError, f"task {type(self).__name__} scoring"):
            metrics = discover_decorated(self, "metric")
            rewards = discover_decorated(self, "reward")
            if runtime is None:
                skipped = [
                    fn.__name__ for fn in (*metrics, *rewards) if requires_runtime(fn)
                ] + [
                    judge.reward_name
                    for judge in judges
                    if requires_runtime(judge.score)
                ]
                if skipped:
                    logger.info(
                        "score: no runtime — skipped runtime-dependent signals: %s",
                        skipped,
                    )
                metrics = [fn for fn in metrics if not requires_runtime(fn)]
                rewards = [fn for fn in rewards if not requires_runtime(fn)]
                judges = [
                    judge for judge in judges if not requires_runtime(judge.score)
                ]

            metric_results = await invoke_all(metrics, available)
            for fn, result in zip(metrics, metric_results):
                if isinstance(result, Mapping):
                    trace.record_metrics(result)
                else:
                    trace.record_metric(fn.__name__, result)
            reward_results = await invoke_all(rewards, available)
            for fn, result in zip(rewards, reward_results):
                weight = getattr(fn, "_vf_weight", 1.0)
                items = (
                    result.items()
                    if isinstance(result, Mapping)
                    else [(fn.__name__, result)]
                )
                for key, value in items:
                    trace.record_reward(key, value, weight)
            judge_results = await invoke_all(
                [judge.score for judge in judges], available
            )
            for judge, result in zip(judges, judge_results):
                items = (
                    result.items()
                    if isinstance(result, Mapping)
                    else [(judge.reward_name, result)]
                )
                for key, value in items:
                    trace.record_reward(key, value, judge.config.weight)

    @classmethod
    def data_type(cls) -> type[TaskData]:
        return concrete_type(cls, TaskData) or TaskData

    @classmethod
    def config_type(cls) -> type[TaskConfig]:
        return concrete_type(cls, TaskConfig) or TaskConfig

    def plugged_judges(self) -> list[Judge]:
        from verifiers.v1.utils.loaders import load_judge

        return [load_judge(config) for config in self.config.judges]

    @classmethod
    def toolsets(cls, config: ConfigT) -> list[Toolset]:
        """Tool servers launched per rollout, each constructed with its config off
        `config` — override and wire explicitly:

            @classmethod
            def toolsets(cls, config: MyTaskConfig) -> list[vf.Toolset]:
                return [SearchToolset(config.tools)]

        A classmethod so consumers can size placement (tunnels) off the class
        before any task instance exists."""
        return []


TaskT = TypeVar("TaskT", bound=Task)
